#server:
#  port: ${PORT:0}

#spring:
#  application.name: dynamic-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8081/eureka
#    registryFetchIntervalSeconds: 1
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}