server:
  port: 8080

spring:
  application.name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1