server:
  port: 8010

spring:
  application.name: service-factory

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
    registryFetchIntervalSeconds: 1
  instance:
    leaseRenewalIntervalInSeconds: 1